---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: mountme2

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-runner
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["restricted"]
    verbs: ["use"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs", "job/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "pods/binding", "pods/log", "pods/status"]
    verbs: ["get", "list", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: mountme2
subjects:
- kind: ServiceAccount
  name: runner
  namespace: mountme2
roleRef:
  kind: ClusterRole
  name: job-runner
  apiGroup: rbac.authorization.k8s.io
