apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: registry-config
  namespace: treasure-hunt
