kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
  namespace: sniff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: nginx:latest
