kind: Deployment
apiVersion: apps/v1
metadata:
  name: victim
  namespace: sniff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
        - name: victim
          image: python:latest
          command: ["tail", "-f", "/dev/null"]
